<div class="contentSec">
<p class="p1"><span class="s1"><b>GraderJoe Privacy Policy</b></span></p>
<p class="p2"><span class="s1">Last Modified: July 17, 2012</span></p>
<p class="p2"><span class="s1">GraderJoe ("GraderJoe," "we," "us", the "<b>Service</b>") respects your privacy, including the privacy of your information. This Privacy Policy explains what information we collect through our website at www.GraderJoe.com (the "Site").<span class="Apple-converted-space"> </span></span></p>
<p class="p2"><span class="s1">By accessing and using the Site, you agree to the terms and conditions of this Privacy Policy. If you do not agree to the terms and conditions of this Privacy Policy, please do not use the Services. If you feel that GraderJoe is not abiding by this Privacy Policy, please contact us at info@GraderJoe.com.<span class="Apple-converted-space"> </span></span></p>
<p class="p1"><span class="s1"><b>1. The Information We Collect And Store</b></span></p>
<p class="p2"><span class="s1">We may collect and store the following information when running the GraderJoe Service:</span></p>
<p class="p2"><span class="s1">When you register an account, we collect some personal information, such as your name and email address.</span></p>
<p class="p2"><span class="s1">We collect and store the files you upload for processing by the GraderJoe Service ("<b>Files</b>").<span class="Apple-converted-space"> </span></span></p>
<p class="p2"><span class="s1">When you use the Service, we automatically record information from your Device, its software, and your activity using the Services. This may include the Device's Internet Protocol ("IP") address, browser type, the web page visited before you came to our website, information you search for on our website, identification numbers associated with your Devices, date and time stamps associated with transactions, system configuration information, metadata concerning your Files, and other interactions with the Service.</span></p>
<p class="p2"><span class="s1">We also use "cookies" to collect information and improve our Services. You can instruct your browser, by changing its options, to stop accepting cookies or to prompt you before accepting a cookie from the websites you visit. If you do not accept cookies, however, you may not be able to use all aspects of the Service.</span></p>
<p class="p1"><span class="s1"><b>2. Personal Information</b></span></p>
<p class="p2"><span class="s1">In the course of using the Service, we may collect personal information that can be used to contact or identify you ("<b>Personal Information</b>"). We use this information to provide you with the Service.</span></p>
<p class="p1"><span class="s1"><b>3. Information Sharing and Disclosure</b></span></p>
<p class="p2"><span class="s1">GraderJoe shares Personal Information with carefully screened third-party service providers to provide you with the products, services and information you have requested. Examples of such third-party service providers are payment processing companies. These third parties may have access to your information only for purposes of performing these tasks on our behalf and under obligations similar to those in this Privacy Policy. As of the date this policy went into effect, we use Amazon's Elastic Compute Cloud as well as their S3 storage service to store some of your information (for example, your Files).<span class="Apple-converted-space"> </span></span></p>
<p class="p2"><span class="s1">GraderJoe may release personal data if the law requires it to do so or in the good</span><span class="s2">-</span><span class="s1">faith belief that such action is necessary to comply with any laws or respond to a court order, subpoena, or search warrant or to protect GraderJoe's rights and interests.<span class="Apple-converted-space"> </span></span></p>
<p class="p2"><span class="s1">We may disclose your non-private, aggregated, or otherwise non-personal information, such as usage statistics of our Service.</span></p>
<p class="p1"><span class="s1"><b>4. Data Retention</b></span></p>
<p class="p2"><span class="s1">After processing, we store your Files for a period of time to allow for you to inform us of problems with the processing. If we do not hear of any problems, we delete the Files. The period of time for which we wait to hear from you will not exceed 60 days from the date of processing. If you notify us of a problem before we delete your Files, we may retain the files until we resolve the problem following which we will delete your Files.</span></p>
<p class="p4"><span class="s1"><b>5. Forums</b></span></p>
<p class="p2"><span class="s1">Our Service may offer publicly accessible community services such as blogs, forums, and wikis. You should be aware that any information you provide in these areas may be read, collected, and used by others who access them. Your posts may remain even after you cancel your account.</span></p>
<p class="p1"><span class="s1"><b>6. Security</b></span></p>
<p class="p2"><span class="s1">The security of your information is important to us. When you enter sensitive information (such as a credit card number) on our order forms, we encrypt the transmission of that information using secure socket layer technology (SSL).</span></p>
<p class="p2"><span class="s1">We follow generally accepted standards to protect the information submitted to us, both during transmission and once we receive it. No method of electronic transmission or storage is 100% secure, however. Therefore, we cannot guarantee its absolute security. If you have any questions about security on our website, you can contact us at info@GraderJoe.com.</span></p>
<p class="p1"><span class="s1"><b>7. Our Policy Toward Children</b></span></p>
<p class="p2"><span class="s1">Our Services are not intended for use by children under the age of 13 and are not directed at such children. We do not knowingly collect Personal Information from children under the age of 13. Please do not register at GraderJoe if you are under the age of 13.</span></p>
<p class="p1"><span class="s1"><b>8. Contacting Us</b></span></p>
<p class="p2"><span class="s1">If you have any questions about this Privacy Policy, please contact us at info@GraderJoe.com.</span></p>
<p class="p1"><span class="s1"><b>9. Changes to our Privacy Policy</b></span></p>
<p class="p2"><span class="s1">We reserve the right to modify our Privacy Policy at any time. If our Privacy Policy changes, the revised policy will be posted on the Site and we will change the 'Last Modified' date at the top of this page to reflect the date of the modification. Please check back periodically. Any changes to our Privacy Policy will become effective upon our posting of the revised Privacy Policy on the Services. Use of the Services following such changes constitutes your acceptance of the revised Privacy Policy then in effect.</span></p>
</div>
