<div class="contentSec">
<p class="p1"><span class="s1"><b>GraderJoe Terms of Service</b></span></p>
<p class="p2"><span class="s1">Last Modified: July 17, 2012</span></p>
<p class="p2"><span class="s1">Welcome to GraderJoe! These terms of service (the "<b>Terms</b>") govern your access to and use of GraderJoe ("<b>we</b>" or "<b>our</b>") websites and Service (the "<b>Service</b>").<span class="Apple-converted-space"> </span></span></p>
<p class="p2"><span class="s1"><b>By using the Service you agree to be bound by these Terms</b>. The Service may change over time or we may stop, suspend, or modify the Service at any time without prior notice to you. We may also remove any content from our Service at our discretion.</span></p>
<p class="p1"><span class="s1"><b>No Resale of Service</b></span></p>
<p class="p2"><span class="s1">Your use of the Service may be for personal purposes only. You will not reproduce, duplicate, copy, sell, resell or exploit any part of the Service, or use or access the Service for any commercial purpose.</span></p>
<p class="p1"><span class="s1"><b>Permission to Use your Files</b></span></p>
<p class="p2"><span class="s1">By using our Service you give us permission to process your files, or share them at your direction. You retain full ownership of your files.</span></p>
<p class="p1"><span class="s1"><b>Sharing Your Files</b></span></p>
<p class="p2"><span class="s1">The Service may provide features that allow you to share your files with others. Please consider carefully what you choose to share. GraderJoe assumes no responsibility for how other users may modify or use your files.</span></p>
<p class="p1"><span class="s1"><b>Your Responsibilities</b></span></p>
<p class="p2"><span class="s1">Please do not upload, download, or share files unless you have the right to do so. You, not GraderJoe, will be fully responsible and liable for what you<span class="Apple-converted-space">  </span>upload, download, or share while using the Service.<span class="Apple-converted-space"> </span></span></p>
<p class="p2"><span class="s1">You must not upload files that contain viruses, worms, corrupt files, Trojan horses, spyware or other forms of corruptive code, or any other content which may compromise the Service.</span></p>
<p class="p2"><span class="s1">You, and not GraderJoe, are responsible for maintaining and protecting all of your files. GraderJoe will not be liable for any loss or corruption of your files.</span></p>
<p class="p2"><span class="s1">Keep your account information current. If your email address, or other information related to your account, changes, you must notify us promptly. <span class="Apple-converted-space"> </span></span></p>
<p class="p2"><span class="s1">In order to use the Service, you must be at least 13 years of age. You represent that you are at least 13 years old. If you are not at least 13 years old, please do not attempt to use, or set up an account to use, the Service.</span></p>
<p class="p1"><span class="s1"><b>Account Security</b></span></p>
<p class="p2"><span class="s1">You will be responsible for the confidentiality and use of your username and password and agree not to transfer or resell your use of or access to the Service to any third party. YOU ARE ENTIRELY RESPONSIBLE FOR MAINTAINING THE CONFIDENTIALITY OF YOUR USERNAME AND PASSWORD AND FOR ANY AND ALL ACTIVITIES (INCLUDING PURCHASES, AS APPLICABLE) THAT ARE CONDUCTED THROUGH YOUR ACCOUNT. You should immediately notify GraderJoe of any unauthorized use of your account. If you wish to protect your transmission of data or files to GraderJoe, it is your responsibility to use a secure encrypted connection to communicate with the Service.</span></p>
<p class="p1"><span class="s1"><b>Unsolicited Ideas, Feedback and Ownership</b></span></p>
<p class="p2"><span class="s1">We appreciate it when users send us feedback. However, please be aware that we may use any feedback, comments, or suggestions you send us or post in our forums without any obligation to you. These Terms do not grant you any rights to use the GraderJoe trademarks, logos, domain names, or other brand features.</span></p>
<p class="p2"><span class="s1">GraderJoe and its associates do not accept or consider unsolicited ideas, including ideas for new or improved products, processes or technologies, product enhancements, advertising and marketing campaigns, promotions or new product names. Please do not send any original materials, suggestions or other items. The sole purpose of this policy is to avoid potential misunderstandings or disputes when GraderJoe's products or marketing efforts might seem similar to ideas submitted to GraderJoe. If, despite our request not to send us your ideas, you still do, then regardless of what your communication states, the following terms shall apply to your idea submission.</span></p>
<p class="p2"><span class="s1">TERMS OF IDEA SUBMISSION</span></p>
<p class="p2"><span class="s1">You agree that: (a) your ideas will automatically become the property of GraderJoe, without compensation to you, (b) GraderJoe can use the ideas for any purpose and in any way, and (c) any information you provide will be considered non-confidential.</span></p>
<p class="p1"><span class="s1"><b>Other Content</b></span></p>
<p class="p2"><span class="s1">The Service may contain links to third-party websites, Service or resources. GraderJoe makes no representations or warranties concerning, and is not liable or responsible in any manner for, any performance, effectiveness or other aspect of such Service or websites.<span class="Apple-converted-space"> </span></span></p>
<p class="p1"><span class="s1"><b>Termination</b></span></p>
<p class="p2"><span class="s1">You can stop using our Service any time. We reserve the right to suspend or end the Service at any time, with or without cause, and with or without notice.<span class="Apple-converted-space"> </span></span></p>
<p class="p1"><span class="s1"><b>GraderJoe is Available "AS-IS"</b></span></p>
<p class="p2"><span class="s1">THE Service IS PROVIDED "AS IS", AT YOUR OWN RISK, WITHOUT EXPRESS OR IMPLIED WARRANTY OR CONDITION OF ANY KIND. WE ALSO DISCLAIM ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT.<span class="Apple-converted-space">  </span>GraderJoe will have no responsibility for any harm to your computer system, loss or corruption of data, or other harm that results from your access to or use of the Service. Some states do not allow the types of disclaimers in this paragraph, so they may not apply to you.</span></p>
<p class="p1"><span class="s1"><b>Limitation of Liability</b></span></p>
<p class="p3"><span class="s1">TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, NEITHER GRADERJOE NOR ANY OF OUR AFFILIATES, DISTRIBUTORS, PARTNERS, LICENSORS, ADVERTISERS OR SPONSORS, NOR OUR OR THEIR DIRECTORS, OFFICERS, EMPLOYEES, CONSULTANTS, AGENTS OR OTHER REPRESENTATIVES, ARE RESPONSIBLE OR LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY, OR PUNITIVE DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS, LOSS OF DATA OR LOST PROFITS), UNDER ANY CONTRACT, NEGLIGENCE, STRICT LIABILITY OR OTHER THEORY ARISING OUT OF OR RELATING IN ANY WAY TO THE SERVICE (INCLUDING, BUT NOT LIMITED TO, ALL MATERIALS INCORPORATED THEREIN AND ALL FEATURES AND FUNCTIONALITY OF THE SERVICE). YOUR SOLE AND EXCLUSIVE REMEDY FOR DISSATISFACTION WITH THE SERVICE IS TO STOP USING THE SERVICE. TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, THE SOLE, EXCLUSIVE AND MAXIMUM LIABILITY OF GRADERJOE ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR THE SERVICE, WHETHER IN CONTRACT, TORT (INCLUDING, WITHOUT LIMITATION, NEGLIGENCE) OR OTHERWISE, SHALL BE $10. Some states do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.</span></p>
<p class="p1"><span class="s1"><b>Modifications</b></span></p>
<p class="p2"><span class="s1">We may revise these Terms from time to time and change any fees or charges for use of the Service. Any changes we make will be effective immediately upon notice. The most current version of the Terms will always be posted on our website. By continuing to access or use the Service after revisions become effective, you agree to be bound by the revised Terms. If you do not agree to the new terms, please stop using the Service.</span></p>
<p class="p1"><span class="s1"><b>Legal Terms</b></span></p>
<p class="p2"><span class="s1">The state and federal courts of Florida are the exclusive forum and venue to resolve any and all disputes arising out of or otherwise relating to these Terms. You consent to personal jurisdiction and venue by the state and federal courts of the State of Florida.</span></p>
<p class="p2"><span class="s1">These Terms constitute the entire agreement between you and GraderJoe governing your use of the Service. In the case of inconsistencies between these Terms and any information included elsewhere, these Terms will always control.<span class="Apple-converted-space"> </span></span></p>
<p class="p2"><span class="s1">The failure of GraderJoe to exercise or enforce any Term will not constitute a waiver of such Term. If any Term is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of these Terms remain in full force and effect.</span></p>
</div>
